// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreOrderBlindBox.Data.Entities;

public partial class Wallet
{
    public int WalletId { get; set; }

    public decimal Balance { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}