// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreOrderBlindBox.Data.Entities;

public partial class Notification
{
    public int NotificationId { get; set; }

    public int? ReceiverId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool IsRead { get; set; }

    public bool IsDeleted { get; set; }

    public virtual User Receiver { get; set; }
}