// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreOrderBlindBox.Data.Entities;

public partial class VoucherCampaign
{
    public int VoucherCampaignId { get; set; }

    public string Name { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public int Quantity { get; set; }

    public int MaximumUserCanGet { get; set; }

    public decimal? PercentDiscount { get; set; }

    public decimal? MaximumMoneyDiscount { get; set; }

    public decimal? MaximumDiscount { get; set; }

    public string Status { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<UserVoucher> UserVouchers { get; set; } = new List<UserVoucher>();
}