// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreOrderBlindBox.Data.Entities;

public partial class Banner
{
    public int BannerId { get; set; }

    public string ImageUrl { get; set; }

    public string Title { get; set; }

    public string CallToActionUrl { get; set; }

    public int? Priority { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime UpdatedDate { get; set; }
}