// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreOrderBlindBox.Data.Entities;

public partial class Image
{
    public int ImageId { get; set; }

    public int? BlindBoxId { get; set; }

    public string Url { get; set; }

    public string Title { get; set; }

    public bool IsMainImage { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual BlindBox BlindBox { get; set; }
}