// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreOrderBlindBox.Data.Entities;

public partial class PreorderCampaign
{
    public int PreorderCampaignId { get; set; }

    public int? BlindBoxId { get; set; }

    public string Slug { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public string Status { get; set; }

    public string Type { get; set; }

    public int? PlacedOrderCount { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool IsDeleted { get; set; }

    public virtual BlindBox BlindBox { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<PreorderMilestone> PreorderMilestones { get; set; } = new List<PreorderMilestone>();

    public virtual ICollection<TempCampaignBulkOrderDetail> TempCampaignBulkOrderDetails { get; set; } = new List<TempCampaignBulkOrderDetail>();
}