// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreOrderBlindBox.Data.Entities;

public partial class PreorderMilestone
{
    public int PreorderMilestoneId { get; set; }

    public int? PreorderCampaignId { get; set; }

    public int MilestoneNumber { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }

    public bool IsDeleted { get; set; }

    public virtual PreorderCampaign PreorderCampaign { get; set; }
}