// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreOrderBlindBox.Data.Entities;

public partial class TempCampaignBulkOrderDetail
{
    public int TempCampaignBulkOrderDetailId { get; set; }

    public int? TempCampaignBulkOrderId { get; set; }

    public int? PreorderCampaignId { get; set; }

    public decimal UnitPriceAtTime { get; set; }

    public int Quantity { get; set; }

    public decimal? UnitEndCampaignPrice { get; set; }

    public virtual PreorderCampaign PreorderCampaign { get; set; }

    public virtual TempCampaignBulkOrder TempCampaignBulkOrder { get; set; }
}